In [47]:
# 一维数组拼接
x=np.array([1, 2, 3])
y=np.array([3, 2, 1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [49]:
z=[99,99,99]
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [54]:
# 拼接二维数组
grid=np.array([[1, 2, 3],
                            [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [56]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [58]:
# 沿固定维度处理数组: vstack, hstack, dstack
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [62]:
t=([[99],
      [99]])
np.hstack([t, grid])

array([[99,  1,  2,  3],
       [99,  4,  5,  6]])

In [78]:
# 数组的分裂; N个分裂点能得到N+1个数组
a=np.array([1, 2, 3, 4, 5, 6, 7, 8])
a1, a2, a3 = np.split(a, [3, 5])
print(a1, a2, a3)

[1 2 3] [4 5] [6 7 8]


In [81]:
# 第一维度的分裂；同理第二维度分裂为np.hsplit，第三维度为np.dsplit
b = np.arange(16).reshape((4, 4))
upper, lower = np.vsplit(b, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
