In [2]:
# 修改子数组，原数组也会被修改
import numpy as np
x2=np.array([[3, 5, 2, 4],
                         [7, 6, 8, 8],
                          [1, 6, 7, 7]])

In [3]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [4]:
x2_sub = x2[:2, :2] 
x2_sub

array([[3, 5],
       [7, 6]])

In [5]:
x2_sub[0,0]=99 
x2_sub

array([[99,  5],
       [ 7,  6]])

In [6]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [12]:
#创建副本
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy[0,0] = 999
x2_sub_copy

array([[999,   5],
       [  7,   6]])

In [14]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])